// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCVtCMN-WY3_SFfFobZTX7udbiCLjqow',
    appId: '1:313810074389:web:87a6092347a6fb7440c71c',
    messagingSenderId: '313810074389',
    projectId: 'nutrifce',
    authDomain: 'nutrifce.firebaseapp.com',
    storageBucket: 'nutrifce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mWZshjWqR_LP8hueN7bUZrx9w_UgEao',
    appId: '1:313810074389:android:6077f234b10b1ebd40c71c',
    messagingSenderId: '313810074389',
    projectId: 'nutrifce',
    storageBucket: 'nutrifce.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBCVtCMN-WY3_SFfFobZTX7udbiCLjqow',
    appId: '1:313810074389:web:95822fecd4f335cc40c71c',
    messagingSenderId: '313810074389',
    projectId: 'nutrifce',
    authDomain: 'nutrifce.firebaseapp.com',
    storageBucket: 'nutrifce.firebasestorage.app',
  );
}
